# Generated by Django 6.0.4 on 2026-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_caseopening_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
