# Generated by Django 6.0.4 on 2026-04-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_img_url'),
        ('shop', '0008_alter_skin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseitem',
            name='wear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.wear'),
        ),
    ]
