# Generated by Django 6.0.4 on 2026-04-12 09:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_alter_inventoryitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('treasury', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GangMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Owner')], default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gangs.gang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gang_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member of gang',
                'verbose_name_plural': 'Members of gang',
                'ordering': ['-role', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GangMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gangs.gang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GangVaultRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('lost', 'Lost')], default='active', max_length=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='gangs.gang')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GangJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='gangs.gang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gang', 'user')},
            },
        ),
    ]
