# Generated by Django 6.0.3 on 2026-04-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_skin_base_price'),
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeoffer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tradeofferitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='traderesponse',
            name='creator_approved',
        ),
        migrations.RemoveField(
            model_name='traderesponse',
            name='message',
        ),
        migrations.RemoveField(
            model_name='traderesponse',
            name='responder_approved',
        ),
        migrations.RemoveField(
            model_name='traderesponse',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='traderesponseitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offer_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='traderesponse',
            name='response_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tradeofferitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='traderesponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traderesponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='traderesponseitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='TradeTransaction',
        ),
    ]
