# Generated by Django 6.0.4 on 2026-04-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_remove_tradeoffer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
