# Generated by Django 6.0.4 on 2026-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_tradeoffer_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
