# Generated by Django 6.0.3 on 2026-04-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_user_inventoryitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
