# Generated by Django 6.0.4 on 2026-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_skin_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('in_inventory', 'In inventory'), ('on_sale', 'On sale'), ('in_cart', 'In cart'), ('in_trade', 'In trade'), ('in_gang', 'In gang'), ('rented_from_gang', 'Rented from gang')], default='in_inventory', max_length=30),
        ),
    ]
