# Generated by Django 6.0.4 on 2026-04-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangs', '0001_initial'),
        ('shop', '0005_alter_inventoryitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='gang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_items', to='gangs.gang'),
        ),
    ]
