# Generated by Django 6.0.4 on 2026-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_inventoryitem_gang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
