# Generated by Django 6.0.4 on 2026-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_skin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
